# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\clicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 210)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ScoreLabel = QtWidgets.QLabel(self.centralwidget)
        self.ScoreLabel.setGeometry(QtCore.QRect(200, 20, 61, 41))
        self.ScoreLabel.setObjectName('ScoreLabel')
        self.ClickBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ClickBtn.setGeometry(QtCore.QRect(120, 80, 75, 23))
        self.ClickBtn.setObjectName("ClickBtn")
        self.BuyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BuyBtn.setGeometry(QtCore.QRect(220, 80, 75, 23))
        self.BuyBtn.setObjectName("BuyBtn")
        self.PriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.PriceLabel.setGeometry(QtCore.QRect(230, 120, 47, 13))
        self.PriceLabel.setObjectName('PriceLabel')
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setToolTipDuration(-2)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ScoreLabel.setText(_translate("MainWindow", "0"))
        self.ClickBtn.setText(_translate("MainWindow", "Кликай!"))
        self.BuyBtn.setText(_translate("MainWindow", "Улучшить"))
        self.PriceLabel.setText(_translate("MainWindow", "50 очков"))
